### ISSUE TITLE
Gulp 4 support

### ISSUE THREAD

**Issue by gauntface** [stevejhiggs/gulp-webpack-typescript-pipeline#2]
Thanks for the awesome module!

I just tried using this with Gulp 4 but it looks like the following is no longer valid:

```
gulp.task('tsPipeline:watch', [], () => {
```

Remove the empty array fixes the problem, but not sure if the array is used for something.

**Comment by stevejhiggs** [comment]
Ideally I'd like to support gulp 3 or gulp 4 and and need to do some looking into that

**Comment by gauntface** [comment]
I don't think the empty array does anything for gulp 3 and this breaks gulp 4, so I *think* you can just remove it and support both.

**Comment by stevejhiggs** [comment]
Sorry this took so long, life got in the way for a bit :)

Your fix was completely correct thanks, I've just published a new version that fixes gulp 4 compatibility
